# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: CentraleLille\CustomFosUserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: CentraleLille\CustomFosUserBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.competence.service:
        class:  CentraleLille\KnowledgeBundle\Service\CompetenceService
        arguments: [ "@doctrine.orm.entity_manager" ]

    form.type.string_search:
        class: CentraleLille\SearchBundle\Form\SearchStringType
        tags:
            - { name: form.type, alias: string_search_type }

    centrale.reservation.calendar_listener:
        class: CentraleLille\ReservationBundle\Event\CalendarEventListener
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents}

    centrale.reservation.event_booker:
        class: CentraleLille\ReservationBundle\Entity\Booking\Strategy\BookManager
        tags:
            - { name: event_booker }
