centrale_lille_machine:
    path: /reservation
    defaults: {_controller:ReservationBundle:Event:reserver}

centrale_lille_add_machine:
    path: /reservation/add_machine
    defaults: {_controller:ReservationBundle:Machine:addMachine}

centrale_lille_salle:
    path: /salle
    defaults: {_controller:ReservationBundle:Default:salle}

centrale_lille_casier:
    path: /casier
    defaults: {_controller:ReservationBundle:Default:casier}

centrale_lille_administration:
    path: /Admin
    defaults: {_controller:ReservationBundle:Default:admin}

centrale_lille_delete_machine:
    path: /reservation/delete_machine/{id}
    defaults: {_controller:ReservationBundle:Machine:deleteMachine}

centrale_lille_profil:
    path: /profil
    defaults: {_controller:ReservationBundle:Default:profil}


