services:
#    custom_fos_user.example:
#        class: CentraleLille\CustomFosUserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    app.project.service:
        class:  CentraleLille\CustomFosUserBundle\Service\ProjectService
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker", "@logger" ]

    app.project.member_voter:
        class: CentraleLille\CustomFosUserBundle\Security\ProjectMemberVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        # public: false

    app.project.leader_voter:
        class: CentraleLille\CustomFosUserBundle\Security\ProjectLeaderVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
        # small performance boost
        # public: false